// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ozoncp/ocp-prize-api/internal/repo (interfaces: Repo)

// Package mocks is a generated GoMock package.
package mocks

import (
	gomock "github.com/golang/mock/gomock"
	prize "github.com/ozoncp/ocp-prize-api/internal/prize"
	reflect "reflect"
)

// MockRepo is a mock of Repo interface
type MockRepo struct {
	ctrl     *gomock.Controller
	recorder *MockRepoMockRecorder
}

// MockRepoMockRecorder is the mock recorder for MockRepo
type MockRepoMockRecorder struct {
	mock *MockRepo
}

// NewMockRepo creates a new mock instance
func NewMockRepo(ctrl *gomock.Controller) *MockRepo {
	mock := &MockRepo{ctrl: ctrl}
	mock.recorder = &MockRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockRepo) EXPECT() *MockRepoMockRecorder {
	return m.recorder
}

// AddPrizes mocks base method
func (m *MockRepo) AddPrizes(arg0 []prize.Prize) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddPrizes", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddPrizes indicates an expected call of AddPrizes
func (mr *MockRepoMockRecorder) AddPrizes(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddPrizes", reflect.TypeOf((*MockRepo)(nil).AddPrizes), arg0)
}

// DescribePrize mocks base method
func (m *MockRepo) DescribePrize(arg0 uint64) (*prize.Prize, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DescribePrize", arg0)
	ret0, _ := ret[0].(*prize.Prize)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribePrize indicates an expected call of DescribePrize
func (mr *MockRepoMockRecorder) DescribePrize(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribePrize", reflect.TypeOf((*MockRepo)(nil).DescribePrize), arg0)
}

// ListPrizes mocks base method
func (m *MockRepo) ListPrizes(arg0, arg1 uint64) ([]prize.Prize, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPrizes", arg0, arg1)
	ret0, _ := ret[0].([]prize.Prize)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPrizes indicates an expected call of ListPrizes
func (mr *MockRepoMockRecorder) ListPrizes(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPrizes", reflect.TypeOf((*MockRepo)(nil).ListPrizes), arg0, arg1)
}

// RemovePrize mocks base method
func (m *MockRepo) RemovePrize(arg0 uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemovePrize", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemovePrize indicates an expected call of RemovePrize
func (mr *MockRepoMockRecorder) RemovePrize(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemovePrize", reflect.TypeOf((*MockRepo)(nil).RemovePrize), arg0)
}
