version: "3"

services:
    pr_db:
        container_name: pr_db
        image: postgres
        restart: always
        environment:
          - POSTGRES_PASSWORD=avK25
          - POSTGRES_USER=postgres
          - POSTGRES_DB=stage
        volumes:
          - .pgdata:/data/postgres
        ports:
          - ${POSTGRES_PORT:-5432}:5432

    zookeeper1:
        image: confluentinc/cp-zookeeper
        ports:
          - "2181:2181"
        environment:
            zk_id: "1"
            ZOOKEEPER_CLIENT_PORT: 32181
            ZOOKEEPER_TICK_TIME: 2000
            ZOOKEEPER_SYNC_LIMIT: 2

    zookeeper2:
        image: confluentinc/cp-zookeeper
        ports:
          - "2182:2182"
        environment:
            zk_id: "1"
            ZOOKEEPER_CLIENT_PORT: 32182
            ZOOKEEPER_TICK_TIME: 2000
            ZOOKEEPER_SYNC_LIMIT: 2
        
        
    kafka1:
        image: confluentinc/cp-kafka
        depends_on:
            - zookeeper1
        ports:
            - "127.0.0.1:9093:9093"
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: "zookeeper1:32181"
            KAFKA_LISTENERS: INTERNAL://kafka1:9092,OUTSIDE://kafka1:9093
            KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka1:9092,OUTSIDE://kafka1:9093
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

    kafka2:
        image: confluentinc/cp-kafka
        depends_on:
            - zookeeper2
        ports:
            - "127.0.0.1:9094:9094"
        environment:
            KAFKA_BROKER_ID: 2
            KAFKA_ZOOKEEPER_CONNECT: "zookeeper2:32182"
            KAFKA_LISTENERS: INTERNAL://kafka2:9092,OUTSIDE://kafka2:9094
            KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka2:9092,OUTSIDE://kafka2:9094
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
        
    prometheus:
        image: prom/prometheus
        ports:
            - "9090:9090"
  
    ocpprizeapi:
        image: ocpprizeapi
        build: "./"
        links:
          - "kafka1:kafka1"
          - "kafka2:kafka2"
          - "prometheus:prometheus"
          - "pr_db:postgres"
        ports:
          - "127.0.0.1:8082:8082"
        command: make test run
        depends_on:
          - pr_db
          - kafka1
          - kafka2
          - prometheus
       