version: "3"

services:
    pr_db:
        container_name: pr_db
        image: postgres
        restart: always
        environment:
          - POSTGRES_PASSWORD=avK25
          - POSTGRES_USER=postgres
          - POSTGRES_DB=stage
        volumes:
          - .pgdata:/data/postgres
        ports:
          - ${POSTGRES_PORT:-5432}:5432

    zookeeper:
        image: confluentinc/cp-zookeeper
        ports:
          - "2181:2181"
        environment:
            zk_id: "1"
            ZOOKEEPER_CLIENT_PORT: 32181
            ZOOKEEPER_TICK_TIME: 2000
            ZOOKEEPER_SYNC_LIMIT: 2
        
        
    kafka:
        image: confluentinc/cp-kafka
        depends_on:
            - zookeeper
        ports:
            - "127.0.0.1:9093:9093"
            - "127.0.0.1:9094:9094"
        environment:
            KAFKA_ZOOKEEPER_CONNECT: "zookeeper:32181"
            KAFKA_LISTENERS: INTERNAL://kafka:9092,OUTSIDE1://kafka:9093,OUTSIDE2://kafka:9094
            KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,OUTSIDE1://kafka:9093,OUTSIDE2://kafka:9094
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE1:PLAINTEXT,OUTSIDE2:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
        
    prometheus:
        image: prom/prometheus
        ports:
            - "9090:9090"
    
    ocpprizeapi:
        image: ocpprizeapi
        build: "./"
        links:
          - "kafka:kafka"
          - "prometheus:prometheus"
        ports:
          - "127.0.0.1:8082:8082"
        command: make test run
        depends_on:
          - pr_db
          - kafka
          - prometheus

        