// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/ocp-prize-api/ocp-prize-api.proto

package ocp_prize_api

import (
	fmt "fmt"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ListPrizeV1Request struct {
	Limit                uint64   `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               uint64   `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListPrizeV1Request) Reset()         { *m = ListPrizeV1Request{} }
func (m *ListPrizeV1Request) String() string { return proto.CompactTextString(m) }
func (*ListPrizeV1Request) ProtoMessage()    {}
func (*ListPrizeV1Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f9f7ba6cff1c934, []int{0}
}

func (m *ListPrizeV1Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPrizeV1Request.Unmarshal(m, b)
}
func (m *ListPrizeV1Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPrizeV1Request.Marshal(b, m, deterministic)
}
func (m *ListPrizeV1Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPrizeV1Request.Merge(m, src)
}
func (m *ListPrizeV1Request) XXX_Size() int {
	return xxx_messageInfo_ListPrizeV1Request.Size(m)
}
func (m *ListPrizeV1Request) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPrizeV1Request.DiscardUnknown(m)
}

var xxx_messageInfo_ListPrizeV1Request proto.InternalMessageInfo

func (m *ListPrizeV1Request) GetLimit() uint64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ListPrizeV1Request) GetOffset() uint64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type ListPrizeV1Response struct {
	Prizes               []*Prize `protobuf:"bytes,1,rep,name=prizes,proto3" json:"prizes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListPrizeV1Response) Reset()         { *m = ListPrizeV1Response{} }
func (m *ListPrizeV1Response) String() string { return proto.CompactTextString(m) }
func (*ListPrizeV1Response) ProtoMessage()    {}
func (*ListPrizeV1Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f9f7ba6cff1c934, []int{1}
}

func (m *ListPrizeV1Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPrizeV1Response.Unmarshal(m, b)
}
func (m *ListPrizeV1Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPrizeV1Response.Marshal(b, m, deterministic)
}
func (m *ListPrizeV1Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPrizeV1Response.Merge(m, src)
}
func (m *ListPrizeV1Response) XXX_Size() int {
	return xxx_messageInfo_ListPrizeV1Response.Size(m)
}
func (m *ListPrizeV1Response) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPrizeV1Response.DiscardUnknown(m)
}

var xxx_messageInfo_ListPrizeV1Response proto.InternalMessageInfo

func (m *ListPrizeV1Response) GetPrizes() []*Prize {
	if m != nil {
		return m.Prizes
	}
	return nil
}

type CreatePrizeV1Request struct {
	Link                 string   `protobuf:"bytes,3,opt,name=link,proto3" json:"link,omitempty"`
	IssueId              uint64   `protobuf:"varint,2,opt,name=issue_id,json=issueId,proto3" json:"issue_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePrizeV1Request) Reset()         { *m = CreatePrizeV1Request{} }
func (m *CreatePrizeV1Request) String() string { return proto.CompactTextString(m) }
func (*CreatePrizeV1Request) ProtoMessage()    {}
func (*CreatePrizeV1Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f9f7ba6cff1c934, []int{2}
}

func (m *CreatePrizeV1Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePrizeV1Request.Unmarshal(m, b)
}
func (m *CreatePrizeV1Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePrizeV1Request.Marshal(b, m, deterministic)
}
func (m *CreatePrizeV1Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePrizeV1Request.Merge(m, src)
}
func (m *CreatePrizeV1Request) XXX_Size() int {
	return xxx_messageInfo_CreatePrizeV1Request.Size(m)
}
func (m *CreatePrizeV1Request) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePrizeV1Request.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePrizeV1Request proto.InternalMessageInfo

func (m *CreatePrizeV1Request) GetLink() string {
	if m != nil {
		return m.Link
	}
	return ""
}

func (m *CreatePrizeV1Request) GetIssueId() uint64 {
	if m != nil {
		return m.IssueId
	}
	return 0
}

type CreatePrizeV1Response struct {
	PrizeId              uint64   `protobuf:"varint,1,opt,name=prize_id,json=prizeId,proto3" json:"prize_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePrizeV1Response) Reset()         { *m = CreatePrizeV1Response{} }
func (m *CreatePrizeV1Response) String() string { return proto.CompactTextString(m) }
func (*CreatePrizeV1Response) ProtoMessage()    {}
func (*CreatePrizeV1Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f9f7ba6cff1c934, []int{3}
}

func (m *CreatePrizeV1Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePrizeV1Response.Unmarshal(m, b)
}
func (m *CreatePrizeV1Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePrizeV1Response.Marshal(b, m, deterministic)
}
func (m *CreatePrizeV1Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePrizeV1Response.Merge(m, src)
}
func (m *CreatePrizeV1Response) XXX_Size() int {
	return xxx_messageInfo_CreatePrizeV1Response.Size(m)
}
func (m *CreatePrizeV1Response) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePrizeV1Response.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePrizeV1Response proto.InternalMessageInfo

func (m *CreatePrizeV1Response) GetPrizeId() uint64 {
	if m != nil {
		return m.PrizeId
	}
	return 0
}

type RemovePrizeV1Request struct {
	PrizeId              uint64   `protobuf:"varint,1,opt,name=prize_id,json=prizeId,proto3" json:"prize_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemovePrizeV1Request) Reset()         { *m = RemovePrizeV1Request{} }
func (m *RemovePrizeV1Request) String() string { return proto.CompactTextString(m) }
func (*RemovePrizeV1Request) ProtoMessage()    {}
func (*RemovePrizeV1Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f9f7ba6cff1c934, []int{4}
}

func (m *RemovePrizeV1Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemovePrizeV1Request.Unmarshal(m, b)
}
func (m *RemovePrizeV1Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemovePrizeV1Request.Marshal(b, m, deterministic)
}
func (m *RemovePrizeV1Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemovePrizeV1Request.Merge(m, src)
}
func (m *RemovePrizeV1Request) XXX_Size() int {
	return xxx_messageInfo_RemovePrizeV1Request.Size(m)
}
func (m *RemovePrizeV1Request) XXX_DiscardUnknown() {
	xxx_messageInfo_RemovePrizeV1Request.DiscardUnknown(m)
}

var xxx_messageInfo_RemovePrizeV1Request proto.InternalMessageInfo

func (m *RemovePrizeV1Request) GetPrizeId() uint64 {
	if m != nil {
		return m.PrizeId
	}
	return 0
}

type RemovePrizeV1Response struct {
	Found                bool     `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemovePrizeV1Response) Reset()         { *m = RemovePrizeV1Response{} }
func (m *RemovePrizeV1Response) String() string { return proto.CompactTextString(m) }
func (*RemovePrizeV1Response) ProtoMessage()    {}
func (*RemovePrizeV1Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f9f7ba6cff1c934, []int{5}
}

func (m *RemovePrizeV1Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemovePrizeV1Response.Unmarshal(m, b)
}
func (m *RemovePrizeV1Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemovePrizeV1Response.Marshal(b, m, deterministic)
}
func (m *RemovePrizeV1Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemovePrizeV1Response.Merge(m, src)
}
func (m *RemovePrizeV1Response) XXX_Size() int {
	return xxx_messageInfo_RemovePrizeV1Response.Size(m)
}
func (m *RemovePrizeV1Response) XXX_DiscardUnknown() {
	xxx_messageInfo_RemovePrizeV1Response.DiscardUnknown(m)
}

var xxx_messageInfo_RemovePrizeV1Response proto.InternalMessageInfo

func (m *RemovePrizeV1Response) GetFound() bool {
	if m != nil {
		return m.Found
	}
	return false
}

type DescribePrizeV1Request struct {
	PrizeId              uint64   `protobuf:"varint,1,opt,name=prize_id,json=prizeId,proto3" json:"prize_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DescribePrizeV1Request) Reset()         { *m = DescribePrizeV1Request{} }
func (m *DescribePrizeV1Request) String() string { return proto.CompactTextString(m) }
func (*DescribePrizeV1Request) ProtoMessage()    {}
func (*DescribePrizeV1Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f9f7ba6cff1c934, []int{6}
}

func (m *DescribePrizeV1Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DescribePrizeV1Request.Unmarshal(m, b)
}
func (m *DescribePrizeV1Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DescribePrizeV1Request.Marshal(b, m, deterministic)
}
func (m *DescribePrizeV1Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DescribePrizeV1Request.Merge(m, src)
}
func (m *DescribePrizeV1Request) XXX_Size() int {
	return xxx_messageInfo_DescribePrizeV1Request.Size(m)
}
func (m *DescribePrizeV1Request) XXX_DiscardUnknown() {
	xxx_messageInfo_DescribePrizeV1Request.DiscardUnknown(m)
}

var xxx_messageInfo_DescribePrizeV1Request proto.InternalMessageInfo

func (m *DescribePrizeV1Request) GetPrizeId() uint64 {
	if m != nil {
		return m.PrizeId
	}
	return 0
}

type DescribePrizeV1Response struct {
	Prize                *Prize   `protobuf:"bytes,1,opt,name=prize,proto3" json:"prize,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DescribePrizeV1Response) Reset()         { *m = DescribePrizeV1Response{} }
func (m *DescribePrizeV1Response) String() string { return proto.CompactTextString(m) }
func (*DescribePrizeV1Response) ProtoMessage()    {}
func (*DescribePrizeV1Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f9f7ba6cff1c934, []int{7}
}

func (m *DescribePrizeV1Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DescribePrizeV1Response.Unmarshal(m, b)
}
func (m *DescribePrizeV1Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DescribePrizeV1Response.Marshal(b, m, deterministic)
}
func (m *DescribePrizeV1Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DescribePrizeV1Response.Merge(m, src)
}
func (m *DescribePrizeV1Response) XXX_Size() int {
	return xxx_messageInfo_DescribePrizeV1Response.Size(m)
}
func (m *DescribePrizeV1Response) XXX_DiscardUnknown() {
	xxx_messageInfo_DescribePrizeV1Response.DiscardUnknown(m)
}

var xxx_messageInfo_DescribePrizeV1Response proto.InternalMessageInfo

func (m *DescribePrizeV1Response) GetPrize() *Prize {
	if m != nil {
		return m.Prize
	}
	return nil
}

// Prize description
type Prize struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	IssueId              uint64   `protobuf:"varint,2,opt,name=issue_id,json=issueId,proto3" json:"issue_id,omitempty"`
	Link                 string   `protobuf:"bytes,3,opt,name=link,proto3" json:"link,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Prize) Reset()         { *m = Prize{} }
func (m *Prize) String() string { return proto.CompactTextString(m) }
func (*Prize) ProtoMessage()    {}
func (*Prize) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f9f7ba6cff1c934, []int{8}
}

func (m *Prize) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Prize.Unmarshal(m, b)
}
func (m *Prize) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Prize.Marshal(b, m, deterministic)
}
func (m *Prize) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Prize.Merge(m, src)
}
func (m *Prize) XXX_Size() int {
	return xxx_messageInfo_Prize.Size(m)
}
func (m *Prize) XXX_DiscardUnknown() {
	xxx_messageInfo_Prize.DiscardUnknown(m)
}

var xxx_messageInfo_Prize proto.InternalMessageInfo

func (m *Prize) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Prize) GetIssueId() uint64 {
	if m != nil {
		return m.IssueId
	}
	return 0
}

func (m *Prize) GetLink() string {
	if m != nil {
		return m.Link
	}
	return ""
}

func init() {
	proto.RegisterType((*ListPrizeV1Request)(nil), "ocp.prize.api.ListPrizeV1Request")
	proto.RegisterType((*ListPrizeV1Response)(nil), "ocp.prize.api.ListPrizeV1Response")
	proto.RegisterType((*CreatePrizeV1Request)(nil), "ocp.prize.api.CreatePrizeV1Request")
	proto.RegisterType((*CreatePrizeV1Response)(nil), "ocp.prize.api.CreatePrizeV1Response")
	proto.RegisterType((*RemovePrizeV1Request)(nil), "ocp.prize.api.RemovePrizeV1Request")
	proto.RegisterType((*RemovePrizeV1Response)(nil), "ocp.prize.api.RemovePrizeV1Response")
	proto.RegisterType((*DescribePrizeV1Request)(nil), "ocp.prize.api.DescribePrizeV1Request")
	proto.RegisterType((*DescribePrizeV1Response)(nil), "ocp.prize.api.DescribePrizeV1Response")
	proto.RegisterType((*Prize)(nil), "ocp.prize.api.Prize")
}

func init() {
	proto.RegisterFile("api/ocp-prize-api/ocp-prize-api.proto", fileDescriptor_2f9f7ba6cff1c934)
}

var fileDescriptor_2f9f7ba6cff1c934 = []byte{
	// 526 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0x5d, 0x6b, 0x13, 0x41,
	0x14, 0x35, 0xdf, 0xf1, 0xc6, 0x28, 0x8c, 0x49, 0x9b, 0x06, 0x85, 0x38, 0x5a, 0x09, 0xc5, 0xec,
	0xd2, 0xf8, 0xa6, 0x82, 0x24, 0xb5, 0x42, 0x41, 0x50, 0xf6, 0xc1, 0x07, 0x5f, 0xca, 0x66, 0x77,
	0xb2, 0x19, 0x9a, 0xcc, 0x8c, 0x3b, 0x93, 0x60, 0x2a, 0x22, 0xf8, 0x17, 0xfc, 0x69, 0xfe, 0x04,
	0xfd, 0x15, 0x3e, 0x49, 0x66, 0xb6, 0xb6, 0x3b, 0xbb, 0x46, 0xe8, 0xdb, 0xde, 0xd9, 0x73, 0xcf,
	0xb9, 0xe7, 0xce, 0x61, 0x60, 0xdf, 0x17, 0xd4, 0xe5, 0x81, 0x18, 0x88, 0x98, 0x9e, 0x93, 0x41,
	0xa6, 0x72, 0x44, 0xcc, 0x15, 0x47, 0x4d, 0x1e, 0x08, 0x47, 0x1f, 0x3a, 0xbe, 0xa0, 0xdd, 0x7b,
	0x11, 0xe7, 0xd1, 0x9c, 0xb8, 0x1b, 0xb8, 0xcf, 0x18, 0x57, 0xbe, 0xa2, 0x9c, 0x49, 0x03, 0xee,
	0x8e, 0x22, 0xaa, 0x66, 0xcb, 0x89, 0x13, 0xf0, 0x85, 0x4b, 0xd8, 0x8a, 0xaf, 0x45, 0xcc, 0x3f,
	0xad, 0x5d, 0xfd, 0x33, 0x18, 0x44, 0x84, 0x0d, 0x56, 0xfe, 0x9c, 0x86, 0xbe, 0x22, 0x6e, 0xe6,
	0xc3, 0x50, 0xe0, 0x31, 0xa0, 0x37, 0x54, 0xaa, 0x77, 0x1b, 0xc5, 0xf7, 0x87, 0x1e, 0xf9, 0xb8,
	0x24, 0x52, 0xa1, 0x16, 0x54, 0xe6, 0x74, 0x41, 0x55, 0xa7, 0xd0, 0x2b, 0xf4, 0xcb, 0x9e, 0x29,
	0xd0, 0x0e, 0x54, 0xf9, 0x74, 0x2a, 0x89, 0xea, 0x14, 0xf5, 0x71, 0x52, 0xe1, 0x23, 0xb8, 0x9b,
	0xe2, 0x90, 0x82, 0x33, 0x49, 0xd0, 0x13, 0xa8, 0x6a, 0x23, 0xb2, 0x53, 0xe8, 0x95, 0xfa, 0x8d,
	0x61, 0xcb, 0x49, 0x79, 0x73, 0x34, 0xde, 0x4b, 0x30, 0xf8, 0x18, 0x5a, 0x47, 0x31, 0xf1, 0x15,
	0xb1, 0x46, 0x41, 0x50, 0x9e, 0x53, 0x76, 0xd6, 0x29, 0xf5, 0x0a, 0xfd, 0x9b, 0x9e, 0xfe, 0x46,
	0x7b, 0x50, 0xa7, 0x52, 0x2e, 0xc9, 0x29, 0x0d, 0x93, 0x51, 0x6a, 0xba, 0x3e, 0x09, 0xf1, 0x10,
	0xda, 0x16, 0x4d, 0x32, 0xcd, 0x1e, 0xd4, 0xb5, 0xd2, 0xa6, 0xc7, 0xb8, 0xaa, 0xe9, 0xfa, 0x24,
	0xc4, 0xcf, 0xa0, 0xe5, 0x91, 0x05, 0x5f, 0xd9, 0xd2, 0xd8, 0x6e, 0x19, 0xd7, 0x7e, 0x8f, 0xcb,
	0xc3, 0x62, 0xef, 0xc6, 0x65, 0xef, 0x00, 0xda, 0x56, 0x6f, 0xa2, 0xd7, 0x82, 0xca, 0x94, 0x2f,
	0x99, 0xe9, 0xac, 0x7b, 0xa6, 0xc0, 0x2f, 0x60, 0xe7, 0x15, 0x91, 0x41, 0x4c, 0x27, 0xd7, 0x11,
	0x3b, 0x86, 0xdd, 0x4c, 0x77, 0x22, 0x77, 0x00, 0x15, 0x8d, 0xd2, 0xbd, 0xff, 0xda, 0xb5, 0x81,
	0xe0, 0xd7, 0x50, 0xd1, 0x35, 0xba, 0x0d, 0xc5, 0xbf, 0xdb, 0x28, 0xd2, 0x70, 0xcb, 0x5e, 0xf3,
	0xae, 0x61, 0xf8, 0xb3, 0x04, 0x8d, 0xb7, 0x81, 0xd0, 0x5c, 0x23, 0x41, 0xd1, 0x0c, 0x1a, 0x57,
	0x72, 0x80, 0x1e, 0x58, 0x33, 0x64, 0x73, 0xd6, 0xc5, 0xdb, 0x20, 0xc6, 0x19, 0x46, 0xdf, 0x7e,
	0xfc, 0xfa, 0x5e, 0xbc, 0x85, 0xc0, 0x5d, 0x1d, 0xba, 0x26, 0x2c, 0xe8, 0x2b, 0xdc, 0xb1, 0x16,
	0x81, 0xf6, 0x2d, 0xaa, 0xfc, 0x35, 0x77, 0x1f, 0xff, 0x0f, 0x96, 0xa8, 0xde, 0xd7, 0xaa, 0xbb,
	0xa8, 0x7d, 0xa9, 0xea, 0x7e, 0xbe, 0xb8, 0xa0, 0x2f, 0x88, 0x41, 0x33, 0x15, 0x33, 0xf4, 0xd0,
	0xe2, 0xcd, 0xcb, 0x72, 0xf7, 0xd1, 0x76, 0x50, 0xda, 0x30, 0xbe, 0x6a, 0x78, 0x0d, 0xcd, 0x54,
	0xcc, 0x32, 0x7a, 0x79, 0x01, 0xce, 0xe8, 0xe5, 0x26, 0xf5, 0xc2, 0xea, 0x41, 0xbe, 0xd5, 0xf1,
	0xe8, 0xc3, 0xcb, 0x88, 0xce, 0x54, 0xf2, 0xcc, 0xf0, 0x73, 0xce, 0x02, 0x61, 0x3d, 0x64, 0xe2,
	0x2c, 0x4a, 0x9f, 0x3c, 0xe7, 0x81, 0x38, 0x35, 0x14, 0xbe, 0xa0, 0x93, 0xaa, 0x7e, 0x6b, 0x9e,
	0xfe, 0x09, 0x00, 0x00, 0xff, 0xff, 0xca, 0x2a, 0x66, 0x94, 0x04, 0x05, 0x00, 0x00,
}
